#!/bin/bash
###############################################################
# simpleX                                                     #
# A simple file explorer using index to browse under terminal #
# Version: 2.0                                                #
# Author: b2ns                                                #
###############################################################

#set default path
[ "$#" != "0" ] && cd "$1" || cd $PWD

#declare global variable and temp file
linecount=""

hidden=false
detail=false
mark=false

clipboard=""
copycut=""
pastepath=""

markpath=""
#prepath=""

cmd=""
parameters=""

filelist=/tmp/simplex.filelist.$$
detaillist=/tmp/simplex.detaillist.$$
clipboardlist=/tmp/simplex.clipboardlist.$$
findlist=/tmp/simplex.findlist.$$
#morelist=/tmp/simplex.morelist.$$

#trap 'rm -f $filelist $detaillist $clipboardlist $findlist $morelist' EXIT
trap 'rm -f $filelist $detaillist $clipboardlist $findlist' EXIT

#define function
showList()
{
  clear
  [ "$PWD" = "$markpath" ] && echo -e "\033[1;36mmarked directory\033[0m"
  #echo -e "\033[1;35msimpleX\033[0m"
  #echo -e "\033[1;30m**************************************\033[0m"

  if [ -s "$findlist" ];then
	cp $findlist $filelist
	:>$findlist
	detail=false
	echo -e "\033[1;36msearch result:\033[0m"
  elif [ "$hidden" = "false" ] && [ "$detail" = "false" ];then
	ls > $filelist
  elif [ "$hidden" = "true" ] && [ "$detail" = "true" ];then
	ls -alh > $detaillist && sed -i '1d' $detaillist
	ls -a > $filelist
  elif [ "$hidden" = "true" ];then
	ls -a > $filelist
  else
	ls -lh > $detaillist && sed -i '1d' $detaillist
	ls > $filelist
  fi

  linecount=$(sed -n '$=' $filelist)

  echo

  index=1
  if [ "$detail" = "false" ];then
	cat $filelist | while read name
	do
	  if [ -L "$name" ];then
		echo -e "[\033[1;32m$index\033[0m] \033[1;36m$name\033[0m" #>> $morelist
	  elif [ -d "$name" ];then
		echo -e "[\033[1;32m$index\033[0m] \033[1;34m$name\033[0m" #>> $morelist
	  elif [ -x "$name" ];then
		echo -e "[\033[1;32m$index\033[0m] \033[1;32m$name\033[0m" #>> $morelist
	  else
		echo -e "[\033[1;32m$index\033[0m] \033[0m$name\033[0m" #>> $morelist
	  fi
	  index=$((index+1))
	done
  else
	cat $detaillist | while read name
	do
	  echo -e "[\033[1;37m$index\033[0m] \033[0m$name\033[0m" #>> $morelist
	  index=$((index+1))
	done
  fi

  #more -d $morelist
  #:> $morelist

  echo
  #echo -e "\033[1;30m**************************************\033[0m"
  #echo -e "\033[1;32m$USER@$HOSTNAME\033[0m:\033[1;34m$PWD\033[0m$ \c"
}

isNumber()
{
  expr "$1" + 1 &> /dev/null && return 0 || return 1
}

noPara()
{
  if [ "$cmd" = "$parameters" ];then
	echo -e "\033[1;31mneed parameters !\033[0m"
	read -r
	return 0
  fi
  return 1
}

paraCheck()
{
  parameters=$(echo "$parameters" | sed 's/*//g')
}

numCheck()
{
  if isNumber "$1" && [ "$1" -gt "0" ] && [ "$1" -le "$linecount" ];then
	return 0
  else
	echo -e "\033[1;31m$1 is out of range! please use index between 1~$linecount !\033[0m"
	read -r
	return 1
  fi
}

existCheck()
{
  if [ -e "$1" ];then
	echo -e "\033[1;31m$1 already exists !\033[0m"
	read -r
	return 1
  fi
  return 0
}

selectAll()
{
  if [ "${parameters%% *}" = "*" ];then
	parameters=$(seq $linecount)
	return 0
  fi
  return 1
}

#isCmd()
#{
  #path=$PATH
  #while : ;do
	#dir=${path%%:*}
	#tmp=""
	#tmp=$(find "$dir" -name "$1" 2>/dev/null)
	#if [ "$tmp" != "" ];then
	  #return 0
	#fi
	#path=${path#*:}
	#[ "$dir" = "$path" ] && break
  #done
  #return 1
#}

Mkfile()
{
  noPara && return 1
  paraCheck

  for name in $parameters
  do
	if existCheck $name;then
	  touch $name
	fi
  done

  return 0
}

Mkdir()
{
  noPara && return 1
  paraCheck

  for name in $parameters
  do
	if existCheck $name;then
	  mkdir $name
	fi
  done

  return 0
}

Mklink()
{
  noPara && return 1
  selectAll
  paraCheck

  for num in $parameters
  do
	if numCheck $num;then
	  filename=$(sed -n ${num}p $filelist)
	  if existCheck "${filename}.link";then
		ln -s "$PWD/$filename" "${filename}.link"
	  fi
	fi
  done
  return 0
}

Delete()
{
  noPara && return 1

  all=false
  selectAll && all=true
  paraCheck

  for num in $parameters
  do
	if numCheck $num;then
	  filename=$(sed -n ${num}p $filelist)
	  if [ "$all" = "false" ];then
		echo -e "\033[1;35m"$filename"\033[0m\033[1;37m will be deleted ? (y/n): \033[0m\c"
		read -r yesno
		[ "$yesno" = "y" ] && (rm "$filename" || rmdir "$filename")
	  else
		rm "$filename" || rmdir "$filename"
	  fi
	fi
  done
  return 0
}

CopyCut()
{
  noPara && return 1

  copycut="$1"
  pastepath="$PWD"
  cp $filelist $clipboardlist
  clipboard=""
  filename=""

  selectAll
  paraCheck

  for num in $parameters
  do
	if numCheck $num;then
	  clipboard="$clipboard $num"
	  name=$(sed -n ${num}p $filelist)
	  filename="$filename\n$name"
	fi
  done

  if [ "$filename" != "" ] ;then
	echo -e "\033[1;35m"$filename"\033[0m"
	echo
	if [ "$copycut" = "copy" ];then
	  echo -e "\033[1;37mhas been copied to the clipboard !\033[0m"
	else
	  echo -e "\033[1;37mhas been cut to the clipboard !\033[0m"
	fi
  fi
  return 0
}

Paste()
{
  if [ "$clipboard" = "" ];then
	  echo -e "\033[1;31mclipboard is empty !\033[0m"
	  read -r
	  return 1
  fi

  ignore=false
  override=false
  rename=false
  choich=""
  yesno=""

  for num in $clipboard
  do
	filename=$(sed -n ${num}p $clipboardlist)
	copyname="$filename"

	if [ "$rename" = "false" ] && [ "$override" = "false" ] && [ "$ignore" = "false" ] && [ -e "$copyname" ];then
		echo -e "\033[1;31m$copyname already exists !\033[0m"
		echo -e "\033[1;37m ignore,override or rename ? (i/o/r): \033[0m\c"
		read  -r choich
		echo -e "\033[1;37m use the same stratege for the rest of files ? (y/n): \033[0m\c"
		read -r yesno
		if [ "$yesno" = "y" ];then
		  case "$choich" in
			"r" )
			  rename=true;;
			"o" )
			  override=true;;
			"i" )
			  ignore=true;;
		  esac
		fi
	fi

	if [ "$choich" = "r" ] || [ "$rename" = "true" ];then
	  i=0
	  while [ -e "$copyname" ];do
		if [ "$filename" != "${filename%%.*}" ];then
		  copyname="${filename%%.*}_$i.${filename#*.}"
		else
		  copyname="${filename}_$i"
		fi
		i=$((i+1))
	  done
	fi

	if ! [ -e "$copyname" ] || ([ "$choich" != "i" ] && [ "$ignore" != "true" ]);then
	  if [ "$copycut" = "copy" ];then
		cp "$pastepath/$filename" "./$copyname"
	  else
		mv "$pastepath/$filename" "./$copyname"
	  fi
	fi

  done

  if [ "$copycut" = "cut" ];then
	clipboard=""
  fi
  return 0
}

Rename()
{
  noPara && return 1

  while :
  do
	num=${parameters%% *}
	parameters=${parameters#* }
	newname=${parameters%% *}
	parameters=${parameters#* }
	if numCheck $num;then
	  oldname=$(sed -n ${num}p $filelist)
	  if existCheck $newname;then
		mv "$oldname" "$newname"
	  fi
	  tmp=${parameters%% *}
	  [ "$parameters" = "$tmp" ] && break
	else
	  break
	fi
  done
  return 0
}

Search()
{
  noPara && return 1

  parameters=${parameters%% *}
  find ./ -mount -maxdepth 1 -iname "$parameters" > $findlist
  sed -i 's/^..//' $findlist

  if [ -s "$findlist" ];then
	return 0
  else
	echo -e "\033[1;31mno such file !\033[0m"
	return 1
  fi
}

Pack()
{
  noPara && return 1

  pkgname=${parameters%% *}
  pkgname=$(echo "$pkgname" | sed 's/*//g')

  if existCheck $pkgname;then
	pkgname=$pkgname
  else
	return 1
  fi

  pkgformat=${pkgname##*.}
  tmp=${pkgname%.*}
  istar=${tmp##*.}

  if [ "$pkgformat" != "zip" ] && ([ "$istar" != "tar" ] || ([ "$pkgformat" != "gz" ] && [ "$pkgformat" != "bz2" ] && [ "$pkgformat" != "xz" ]));then
	echo -e "\033[1;31mthe format of compressed file must be :\n*.zip *.tar.gz *.tar.bz2 *.tar.xz !\033[0m"
	read -r
	return 1
  fi

  parameters=${parameters#* }
  selectAll
  paraCheck

  i=0
  for num in $parameters
  do
	if numCheck $num;then
	  filename=$(sed -n ${num}p $filelist)
	  array[$i]="$filename"
	  i=$((i+1))
	else
	  return 1
	fi
  done
  
  case "$pkgformat" in
	"gz" )
	  tar -zcvf "$pkgname" "${array[@]}";;
	"bz2" )
	  tar -jcvf "$pkgname" "${array[@]}";;
	"xz" )
	  tar -Jcvf "$pkgname" "${array[@]}";;
	"zip" )
	  zip -r "$pkgname" "${array[@]}";;
  esac

  for((j=0;j<i;j++));do
	array[$j]=""
  done
  return 0
}

Unpack()
{
  noPara && return 1

  selectAll
  paraCheck

  for num in $parameters
  do
	if numCheck $num;then
	  filename=$(sed -n ${num}p $filelist)
	  pkgformat=${filename##*.}
	  if [ "$filename" = "$pkgformat" ] ;then
		echo -e "\033[1;35m$filename \033[0m\033[1;31mcan't be decompressed !\033[0m"
		read -r
		continue
	  fi

	  dirname=${filename%%.*}

	  if existCheck $dirname;then
		mkdir "$dirname"
	  else
		continue
	  fi

	  case "$pkgformat" in
		"gz" )
		  tar -zxvf "$filename" -C "$dirname";;
		"bz2" )
		  tar -jxvf "$filename" -C "$dirname";;
		"xz" )
		  tar -Jxvf "$filename" -C "$dirname";;
		"zip" )
		  unzip -d "$dirname" "$filename";;
		* )
		  rmdir "$dirname"
		echo -e "\033[1;35m$filename \033[0m\033[1;31mcan't be decompressed !\033[0m"
		read -r
		;;
	  esac
	fi
  done
  return 0
}

Play()
{
  ./"$filename" 2> /dev/null || xdg-open "$filename" 2> /dev/null || echo -e "\033[1;31mcan't open \033[0m\033[1;35m$filename\033[0m\033[1;31m using default App !\nyou may choose another App to open it by inputting :\033[0m\n               AppName index"
  read -r 
}

cmdPlay()
{
  if [ "$cmd" = "$parameters" ];then
	$cmd
	read -r
	return 0
  fi

  prefix="n"
  filenum=$(echo $parameters |grep -o "$prefix[0-9]\{1,\}")
  for num in $filenum
  do
	num=${num#?}
	if numCheck $num;then
	  filename=$(sed -n ${num}p $filelist)
	  parameters=$(echo $parameters | sed "s/$prefix[0-9]\{1,\}/$filename/")
	else
	  return 1
	fi
  done

  CMD="$cmd $parameters"
  eval $CMD
  read -r

  return 0
}

Shortcut()
{
  echo -e "\033[1;33mSHORTCUT:\033[0m"
  echo " use index(.e.g 1,2,3,4) to select a item"
  echo " 'help'                       show help"
  echo " 'shortcut'                   show shortcut"
  echo " '..' or 'up'                 go upper directory"
  echo " '-' or 'back'                go back"
  echo " '.' or 'r'                   refresh screen"
  echo " '~' or 'home'                go home"
  echo " '/' or 'root'                go root"
  echo " 'm' or 'mark'                mark a directory"
  echo " 'g' or 'goto'                goto the marked directory"
  echo " 'a' or 'all'                 show hidden files"
  echo " 'll'                         show detail"
  echo " 'mkfile'                     make empty files"
  echo "          mkfile name1 name2 ..."
  echo 
  echo " 'mkdir'                      make directories"
  echo "          mkdir name1 name2 ..."
  echo 
  echo " 'mklink'                     make soft link"
  echo "          mklink index1 index2 ... or mklink * "
  echo 
  echo " 'del'                        delete"
  echo "          del index1 index2 ... or del * "
  echo 
  echo " 'copy'                       copy to clipboard"
  echo "          copy index1 index2 ... or copy * "
  echo 
  echo " 'cut'                        cut to clipboard"
  echo "          cut index1 index2 ... or cut * "
  echo 
  echo " 'p' or 'paste'               paste"
  echo " 'rn'                         rename"
  echo "          rn index1 name1 index2 name2 ..."
  echo 
  echo " 'se'                         search"
  echo "          se patten"
  echo 
  echo " 'pack'                       compress"
  echo "          pack name index1 index2 ... or pack name * "
  echo 
  echo " 'unpack'                     decompress"
  echo "          unpack index1 index2 ... or unpack * "
  echo 
  echo " 'q' or 'quit' or 'exit'      exit simpleX"
  return 0
}

Help()
{
  echo -e "\033[1;33mHELP:\033[0m"
  echo "1.the initial path will be the current path,you can start with other path by doing :"
  echo "          simplex path"
  echo "2.you must use index(e.g. 2,45,998,142857) instead of file's name to select a file"
  echo "3.default App is used to open a file"
  echo "4.after inputting 'a' or 'll' to show hidden file and detail,you can input it again to hide"
  echo "5.space and blank is not allowed while you name a file"
  echo "6.you can list files match certain patter by using 'find',and deal with them all by using '*' afterwards such as del *, copy *,pack name *"
  echo "7.only support *.tar.gz,*.tar.bz2,*.tar.xz and *.zip"
  echo "8.all common commands under terminal are supported,you can use them as long as you like;Besides,while dealing with files,you can use a index starting with letter 'n'(e.g. n1,n23,n456) to represent a certen file,for example: "
  echo "    if there is a file named 'main.js' and the index of it is 23,you can do anything like :"
  echo "          vim main.js or vim n23"
  echo "          ls -l main.js or ls -l n23"
  echo "          cp main.js hello.js or cp n23 hello.js"
  echo "          rm -rf n23"
  echo "          chmod 640 n23"
  echo '          echo {"name": "simpleX","array": [1,2,3]} > n23'
  echo "          cat n23 | grep -E '[0-9]+'"
  echo "          tar -zcvf main.tar.gz n23"
  return 0
}

Broswer()
{
  showList

  while :
  do
	
	#echo -e "\033[1;32m$USER@$HOSTNAME\033[0m:\033[1;34m$PWD\033[0m$ \c"
	echo -e "\033[1;32m$USER@\033[0m\033[1;35msimpleX\033[0m:\033[1;34m$PWD\033[0m$ \c"
	read -r input
	cmd=${input%% *}
	parameters=${input#* }

	if isNumber "$input"
	then
	  if [ "$input" -gt "$linecount" ] || [ "$input" -le "0" ]
	  then
		echo -e "\033[1;31mout of range !\033[0m"
		echo -e "\033[1;31mplease use index between 1~$linecount !\033[0m"
		read -r
	  else
		filename=$(sed -n ${input}p $filelist)
		[ -d "$filename" ] && cd "$filename" && showList || Play
	  fi
	elif [ "$input" = "" ] 
	then
	  continue
	elif [ "$input" = ".." ] || [ "$input" = "up" ]
	then
	  cd ..
	  showList
	elif [ "$input" = "-" ] || [ "$input" = "back" ]
	then
	  cd -
	  showList
	elif [ "$input" = "." ] || [ "$input" = "r" ]
	then
	  showList
	elif [ "$input" = "/" ] || [ "$input" = "root" ] 
	then
	  cd /
	  showList
	elif [ "$input" = "~" ] || [ "$input" = "home" ] 
	then
	  cd ~
	  showList
	elif [ "$input" = "m" ] || [ "$input" = "mark" ] 
	then
	  prepath="$markpath"
	  markpath="$PWD"
	  echo -e "\033[1;37mthis directory has been marked !\033[0m"
	  read -r
	elif [ "$input" = "g" ] || [ "$input" = "goto" ] 
	then
	  if [ "$markpath" != "" ];then
		#[ "$PWD" != "$markpath" ] && prepath="$PWD" && cd "$markpath" || cd $prepath
		cd "$markpath"
		showList
	  else
		echo -e "\033[1;31mno directory is marked !\033[0m"
		read -r
	  fi
	elif [ "$input" = "a" ] || [ "$input" = "all" ] 
	then
	  [ "$hidden" = "true" ] && hidden=false || hidden=true
	  showList
	elif [ "$input" = "ll" ]
	then
	  [ "$detail" = "true" ] && detail=false || detail=true
	  showList
	elif [ "$input" = "p" ] || [ "$input" = "paste" ] 
	then
	  Paste && showList
	elif [ "$input" = "help" ] 
	then
	  Help
	elif [ "$input" = "shortcut" ] 
	then
	  Shortcut
	elif [ "$input" = "q" ] || [ "$input" = "quit" ] || [ "$input" = "exit" ] 
	then
	  clear
	  break
	elif [ "$cmd" = "mkfile" ] 
	then
	  Mkfile && showList
	elif [ "$cmd" = "mkdir" ] 
	then
	  Mkdir && showList
	elif [ "$cmd" = "mklink" ] 
	then
	  Mklink && showList
	elif [ "$cmd" = "del" ]
	then
	  Delete && showList
	elif [ "$cmd" = "copy" ] # || [ "$cmd" = "cp" ] 
	then
	  CopyCut "copy"
	elif [ "$cmd" = "cut" ] 
	then
	  CopyCut "cut"
	elif [ "$cmd" = "rn" ] # || [ "$cmd" = "rename" ] 
	then
	  Rename && showList
	elif [ "$cmd" = "se" ]  #|| [ "$cmd" = "search" ]
	then
	  Search && showList
	elif [ "$cmd" = "pack" ] 
	then
	  Pack && showList
	elif [ "$cmd" = "unpack" ] 
	then
	  Unpack && showList
	else
	  cmdPlay && showList
	#else
	  #echo -e "\033[1;31munknown command !\033[0m"
	  #read -r
	fi
  done
}

#main function
Broswer

exit 0
